version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
tasks:
  - name: ansible create directory with mode setting example
    file:
      path: /tmp/devops_directory
      state: directory
      mode: "u=rw,g=wx,o=rwx"
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

